spring.application.name=back
spring.datasource.url=jdbc:postgresql://localhost:5432/checkchow_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=vD3y8hQp9kZ4s2aF6t7E1nM0bXc4R8uP
jwt.expiration=3600000